// <auto-generated />
namespace GISCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rel_RiscoControle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rel_RiscoControle));
        
        string IMigrationMetadata.Id
        {
            get { return "202002042205167_Rel_RiscoControle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
