// <auto-generated />
namespace GISCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CriarREL_RiscoDanosSaude : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriarREL_RiscoDanosSaude));
        
        string IMigrationMetadata.Id
        {
            get { return "202002021303118_CriarREL_RiscoDanosSaude"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
