// <auto-generated />
namespace GISCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class motivo2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(motivo2));
        
        string IMigrationMetadata.Id
        {
            get { return "202102210057063_motivo2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
