// <auto-generated />
namespace GISCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class motivo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(motivo));
        
        string IMigrationMetadata.Id
        {
            get { return "202102210042258_motivo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
